
networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true

volumes:
  storage_data:

services:
  storage:
    build: ./storage
    volumes:
      - storage_data:/var/storage
    networks:
      - private
    